import type { Config } from "tailwindcss";

export default <Config>{
  content: [
    "./app/components/**/*.{vue,js,ts}",
    "./app/layouts/**/*.vue",
    "./app/pages/**/*.vue",
    "./app/app.vue",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#1b1c19",
        "surface-variant": "#e4e2dd",
        "primary-fixed-dim": "#ffb59e",
        "surface-tint": "#a0401f",
        "surface-dim": "#dbdad5",
        "secondary-fixed-dim": "#b4cdb8",
        "surface-container": "#f0eee9",
        tertiary: "#614504",
        "inverse-on-surface": "#f2f1ec",
        "on-tertiary-container": "#ffd993",
        "surface-container-high": "#eae8e3",
        "inverse-surface": "#30312e",
        secondary: "#4d6453",
        "primary-fixed": "#ffdbd0",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f5f3ee",
        "on-primary-fixed-variant": "#802909",
        "on-tertiary-fixed-variant": "#5d4201",
        "on-surface-variant": "#56423c",
        outline: "#8a726b",
        surface: "#fbf9f4",
        "on-primary-fixed": "#3a0b00",
        "tertiary-fixed-dim": "#e9c176",
        "on-primary": "#ffffff",
        "on-surface": "#1b1c19",
        "primary-container": "#a44322",
        "on-secondary-fixed-variant": "#364c3c",
        "secondary-fixed": "#d0e9d4",
        "on-primary-container": "#ffd4c7",
        background: "#fbf9f4",
        "surface-container-highest": "#e4e2dd",
        "on-secondary": "#ffffff",
        "surface-bright": "#fbf9f4",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#ffb59e",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#261900",
        "error-container": "#ffdad6",
        "tertiary-container": "#7b5d1c",
        "on-secondary-fixed": "#0b2013",
        primary: "#842c0c",
        "on-secondary-container": "#516857",
        "outline-variant": "#ddc0b8",
        error: "#ba1a1a",
        "on-error-container": "#93000a",
        "secondary-container": "#cde6d1",
        "tertiary-fixed": "#ffdea5",
        "brass-tint": "#F2E8D5",
        "ink-green": "#1B3022",
      },
      borderRadius: { DEFAULT: "0.125rem", lg: "0.25rem", xl: "0.5rem", full: "0.75rem" },
      spacing: { "margin-desktop": "64px", "margin-mobile": "16px", unit: "8px", gutter: "24px" },
      fontFamily: {
        "display-lg": ["Bodoni Moda", "serif"],
        "headline-sm": ["Bodoni Moda", "serif"],
        "headline-md": ["Bodoni Moda", "serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "label-ledger": ["Space Mono", "monospace"],
        "price-display": ["Space Mono", "monospace"],
      },
    },
  },
};
